{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ping-to-nuageup-app
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: netshoot
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ (index .Values.networkPolicy.from 0).cidr }}
{{- end }}
